
services:
  db:
    image: postgres:15
    container_name: db
    ports:
      - "5432:5432"
    env_file:
      - ./backend/.env
    volumes:
      - ./data/db:/var/lib/postgresql/data
    networks:
      - default
    restart: always

networks:
  default:
    driver: bridge

volumes:
  db:
    driver: local

