services:
  db:
    image: postgres:15
    container_name: db
    ports:
      - "5432:5432"
    env_file:
      - ./backend/.env
    volumes:
      - ./data/db:/var/lib/postgresql/data
    networks:
      - default
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "5050:80"
    env_file:
      - ./backend/.env
    networks:
      - default
    restart: always
    depends_on:
      - db

networks:
  default:
    driver: bridge

volumes:
  db:
    driver: local
