name: Prettier Format

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  PrettierFormat:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Extract Branch Name
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Install Dependencies - Backend
        working-directory: ./backend
        run: npm install

      - name: Run Prettier - Backend
        working-directory: ./backend
        run: |
          npm run format
      
      - name: Pushing Changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          if git diff --cached --quiet; then
            echo "Nothing to commit."
          else
            git commit -m "Prittier formating" || true
            git push origin HEAD:${{ steps.extract_branch.outputs.branch }}
          fi
