name: Prettier Format

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Install Dependencies
        run: npm install prettier@3.3.3

      - name: Enter Backend folder
        run: cd ./backend

      - name: Run Prettier formater
        run: |
          ls -al
          cat package.json